all:
  hosts:
    master01:
      ansible_host: 172.31.38.33
      ip: 172.31.38.33
      access_ip: 172.31.38.33
    node01:
      ansible_host: 172.31.47.103
      ip: 172.31.47.103
      access_ip: 172.31.47.103
    node02:
      ansible_host: 172.31.36.148
      ip: 172.31.36.148
      access_ip: 172.31.36.148
  children:
    kube_control_plane:
      hosts:
        master01:
    kube_node:
      hosts:
        node01:
        node02:
    etcd:
      hosts:
        master01:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
